### ISSUE TITLE
Tooltips sometimes get stuck.

### ISSUE THREAD

**Issue by ghost** [php-integrator/atom-tooltips-legacy-php56#10]
When this happens, moving the mouse around has no effect. Scrolling or changing tabs does remove the tooltip. This makes me suspect that the mouseout event isn't always being sent.
##

**Comment by Gert-dev** [comment]
Doesn't seem to be occurring anymore in 1.0.

**Comment by Gert-dev** [comment]
In rare cases this still appears.

**Comment by Gert-dev** [comment]
This functionality is now part of the base package and it was fixed there.
