### ISSUE TITLE
Blade? template bug + Feature Request

### ISSUE THREAD

**Issue by maximumver** [php-integrator/atom-tooltips-legacy-php56#27]
Hi, 
There is a problem with stuff like this( its kind of blade template? i don't use it usually just was looking):

> `@extends('layouts.base')
> 
> @section('content')
>   @include('partials.page-header')
> 
>   @if (!have_posts())
>     <div class="alert alert-warning">
>       {{ __('Sorry, no results were found.', 'sage') }}
>     </div>
>     {!! get_search_form(false) !!}
>   @endif
> 
>   @while (have_posts()) @php(the_post())
>     @include ('partials.content-'.(get_post_type() !== 'post' ? get_post_type() : get_post_format()))
>   @endwhile
> 
>   {!! get_the_posts_navigation() !!}
> @endsection
> `

When i hover the cursor over the methods documentation doesn't appear!
This is Sage theme of Roots.io
https://roots.io/sage/

Feature request: is it possible to make appear documentation & parameter suggestions not on hover but on shortkeys?
Like in PhpStorm.  Maybe adding this as an option.
Maybe this will also reduce hardware usage & will speed up everything on slow PCs.
I mean i don't always need suggestions, but when i need them it's ok to wait some sec until it will appear.
So no need to calc cursor position continuously( i don't really know if it works in that way), start the process after short-key combination like 'ctrl+q', 'ctrl+p'. 
I understand that cold start will be slower, i am really ok with that as i've said don't need this immediatly. Some little delay is ok.
As i've said before i have no idea if it will help to speed up things on slow machines, but if yes, even a little bit, please add this feature :)
Another thing: is it possible to make hover stuff remain after moving cursor, for example make description of method appear in some kind of sidebar thats doesn't disappear until i click some btn like (x)?

Also i was the one who made issues about CPU issues on enter key & later wordpress not indexing fully ( yeah i do complain sometimes), breaking somewhere in the middle. Just want to say that now it's much faster & after some of your latest updates( maybe penultimate one) i think when you fixed some interpolated strings.. wordpress finally indexes competely!!  
Thank you for your hardwork! 🥇 
As i've said before you created best set of packages for php development for atom. 
This stuff must be included by default :)

Sorry if i've put this in the wrong place or if i ask you too much. You have done already so much stuff that i don't really know what is too much for you,  for me you are doing some tough magic stuff right here.

**Comment by Gert-dev** [comment]
Thanks for the compliment and nice to hear that it's now much faster for you! With 2.0 the core became a socket server, which seems to respond much faster than spawning processes all the time.

About the blade templates: I'll have to investigate that, I've had some other requests about other template languages as well. At the moment I don't really think it's working properly anywhere. I remember another user which was using plain PHP templates that could get it mostly working, but it depends on whether the syntax highlighting package for the template language properly separates the PHP code bits from the rest so they can be recognized as PHP code. Is there any specific highlighting package you're using for this template language?

About the ability to specify a shortcut, I've [created a new ticket about that](https://github.com/php-integrator/atom-tooltips/issues/28) as well as [about disabling tooltips on hover[(https://github.com/php-integrator/atom-tooltips/issues/29). 

For having a sidebar open, IIRC PhpStorm opens some kind of persistent window with the documentation when you use a specific keyboard shortcut or control-hover on an item. I think we'll also need to move to something similar as currently, the user can't move his cursor on the docblock, so clicking links inside it (which could be added in the future) as well as scrolling large docblocks won't work with the current approach. There is also https://github.com/php-integrator/atom-tooltips/issues/23 which talks about this.

**Comment by maximumver** [comment]
Thanx!
>  Is there any specific highlighting package you're using for this template language?
No. I was just watching how that theme is done, opened it with Atom & saw those templates didn't show any hover documentation, but i could navigate to definition! php-integrator-navigation was working.

**Comment by Gert-dev** [comment]
Hello! I'm moving all relevant tickets from this repository to the base package as this functionality is now part of the base package.

I don't think there is anything left to implement for this ticket. In any case, in base 3.0 the tooltips are now displayed in a dock, which also allows using the keyboard to trigger them and to scroll through large docblocks.

If there are any other issues you encounter or suggestions you have, feel free to post them on the base package issue tracker.
