### ISSUE TITLE
Allow triggering tooltips via a shortcut

### ISSUE THREAD

**Issue by Gert-dev** [php-integrator/atom-tooltips-legacy-php56#28]

**Comment by curtisblackwell** [comment]
I just came here to request that tooltips be triggered the same way as php-integrator/atom-navigation, when hovering and holding a key down.

Is that what this is about? If not, should I create a separate issue?

**Comment by Gert-dev** [comment]
Not strictly, but what you're suggesting is something that has also crossed my mind. Also related to this is #23.

Feel free to create a new ticket about it, though, since there is no actual ticket about it.

**Comment by Gert-dev** [comment]
Hello! I'm moving all relevant tickets from this repository to the base package as this functionality is now part of the base package.

I see that this one has basically been implemented in base package 3.0: tooltips are now displayed in a scrollable dock and are triggered via an intention (via the keyboard).
