### ISSUE TITLE
Add support for triggering tooltips on hover + holding a button

### ISSUE THREAD

**Issue by curtisblackwell** [php-integrator/atom-tooltips-legacy-php56#30]
It would be great if tooltips could be triggered the same way as php-integrator/atom-navigation, when hovering and holding a key down.

As they currently behave, tooltips are sometimes annoying and cover up what I'm actually working on.

**Comment by marksagal** [comment]
+1

Having problem if phpdoc description is very long, cannot scrolldown the tooltip. So I think this enhancement will be so useful. :)

**Comment by marksagal** [comment]
I temporarily unset overflow-y and max-height to show full documentation on hover because its not possible to use scroll.

**Comment by Gert-dev** [comment]
Hello! I'm moving all relevant tickets from this repository to the base package as this functionality is now part of the base package.

I see that this one has basically been implemented in another way in base package 3.0: tooltips are now displayed in a scrollable dock, causing them to no longer get in the way and be triggerable via the keyboard.
